version: '3.8'

services:
  postgres_container:
    image: postgres:16
    container_name: bookwavedb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - bookwave_bridge_network

  springboot_app:
    build: .
    container_name: bookwave_app
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_SERVICE_ACCOUNT_KEY_PATH: /app/cred.json
      BOOK_FOLDER_ID: ${BOOK_FOLDER_ID}
      AUTHOR_FOLDER_ID: ${AUTHOR_FOLDER_ID}
      USER_FOLDER_ID: ${USER_FOLDER_ID}
      BLOG_FOLDER_ID: ${BLOG_FOLDER_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    volumes:
      - ./cred.json:/app/cred.json
    depends_on:
      - postgres_container
    networks:
      - bookwave_bridge_network

volumes:
  postgres-data:

networks:
  bookwave_bridge_network:
    driver: bridge
