spring:
  application:
    name: BookWaveBackend
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_DB}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# File
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 2MB
      max-request-size: 3MB

# Google Drive Api
google:
  service-account-key-path: ${GOOGLE_SERVICE_ACCOUNT_KEY_PATH}
  folders:
    book: ${BOOK_FOLDER_ID}
    author: ${AUTHOR_FOLDER_ID}
    user: ${USER_FOLDER_ID}
    blog: ${BLOG_FOLDER_ID}

# Port
server:
  port: 9090